services:
  postgres:
    image: bitnami/postgresql:13.16.0
    container_name: casa_de_lei-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=casa_de_lei
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
